"""Create users and journal table

Revision ID: 751aaa8f655a
Revises: b3ed61dbfd2c
Create Date: 2024-08-24 21:24:15.502384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '751aaa8f655a'
down_revision: Union[str, None] = 'b3ed61dbfd2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('woman', 'doctor', name='user_roles'), nullable=False),
    sa.Column('num_of_pregnancies', sa.Integer(), nullable=False),
    sa.Column('num_of_failed_pregnancies', sa.Integer(), nullable=False),
    sa.Column('first_time_pregnancy', sa.Boolean(), nullable=False),
    sa.Column('prev_failed_pregnancies', sa.Boolean(), nullable=False),
    sa.Column('med_conditions', sa.Enum('diabetes', 'high blood pressure', 'asthma', 'fertility issues', 'mental health conditions', 'obesity', 'other', name='med_conditions_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('doctor_patient',
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], )
    )
    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journals_date'), 'journals', ['date'], unique=False)
    op.create_index(op.f('ix_journals_id'), 'journals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journals_id'), table_name='journals')
    op.drop_index(op.f('ix_journals_date'), table_name='journals')
    op.drop_table('journals')
    op.drop_table('doctor_patient')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
